# Simple workflow for building and deploying static content to GitHub Pages
name: Build and Deploy to Pages

on:
  # Runs on pushes targeting the master branch
  push:
    branches:
      - master

jobs:
  # Build job to create the production build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  # Deploy job to deploy the production build to the gh-pages branch
  deploy:
    needs: build  # The deploy job depends on the build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout the gh-pages branch
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist  # Download the build artifact from the previous job
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push
